### ISSUE TITLE
Make H3 connection settings configurable in H3 Harvest Agent

### ISSUE THREAD

**Issue by obrienben** [DIA-NZ/webcurator#65]
Make the connection details for H3 configurable in the H3 Harvest Agent through the wct-agent.properties.
- host
- port
- username
- password

**Comment by hannakoppelaar** [comment]
It's going to be a bit more involved than anticipated, since these config variables are used in a static context, which is something that Spring doesn't like. I'll need to do a bit of refactoring here.

**Comment by hannakoppelaar** [comment]
@obrienben @kurtlenfesty I would like your feedback here. I noticed that in the current architecture we have the Spring-managed bean HarvestAgentH3 that acts as an abstraction for a H3 instance. The HarvestAgentH3 does not actually know anything about H3 though. It uses another class to talk to H3: HarvesterH3. So far, so good. 

However, HarvesterH3 has another function, which seems to be at odds with it's role as a wrapper for H3: it represents a single crawl job in H3. Although this is somewhat confusing, it doesn't lead to problems right away, until you try to make the H3 connection settings configurable. Wherever you're going to initialise those settings variables, it will become messy, since it will involve passing those on to every HarvesterH3 method. You can't pass them to a constructor just once and be done with it, because talking to H3 involves static methods (which makes sense). And you can't turn HarvesterH3 into a singleton because of how it also represents crawl jobs.

I feel we should rewrite this bit and put all H3 communication in HarvestAgentH3 and simplify HarvestH3 to only be a representation of a crawl job. This would involve looking at the interfaces and abstract classes higher up, so it's not completely trivial.

Does this make sense to you?

We could of course for now just go with a straightforward and messy solution and refactor/redesign this bit later, but I'm hesitant to add to technical debt here.

**Comment by kurtlenfesty** [comment]
I've made changes to support having the H3 instance parameters configurable in this branch: https://github.com/DIA-NZ/webcurator/tree/feature/65_H3-connection-settings-configurable

**Comment by kurtlenfesty** [comment]
@hannakoppelaar See my commit message for a detailed description of what I've done. I won't be able to do any coding for the next two weeks but I can check github. You may be correct in trying to separate the HarvesterH3 into a crawl job class and a wrapper for H3. Or you may want to leave it as it is.

**Comment by kurtlenfesty** [comment]
@obrienben I was going to hold off documenting this change until it has been finalised. The documentation would go in the v2 documentation (if it even needs to be documented, since it's just changing values in a H3 agent local_config.properties file).

**Comment by kurtlenfesty** [comment]
Created pull request for this issue: https://github.com/DIA-NZ/webcurator/pull/76

**Comment by kurtlenfesty** [comment]
Closing issue as pull request has been merged.
